version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: ghcr.io/mb-group/mygpt-backend:amd64
    command: >
      bash -c "dockerd >/dev/null 2>&1 & sleep 10
      && python manage.py migrate --fake sessions zero
      && python manage.py migrate --fake-initial
      && python manage.py collectstatic --no-input
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./libraries:/media
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  frontend:
    image: ghcr.io/mb-group/mygpt-frontend:amd64
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy