name: Frontend create latest manifest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker	login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: create manifest 
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ghcr.io/mb-group/mygpt-frontend:latest
          sources: |
            ghcr.io/mb-group/mygpt-frontend:amd64
            ghcr.io/mb-group/mygpt-frontend:arm64