name: Installation with Docker images 

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: login to github docker registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install with docker-compose    
      uses: isbang/compose-action@v1.5.1
      with:
        compose-file: ./installation/windows/docker-compose.yml